# This file was generated by GoReleaser. DO NOT EDIT.
cask "pray" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "ee50efde97be84147025ad8b6dc8a088566234d7266eefbb8f11d40d0701f895"
      url "https://github.com/jamesmagoo/pray-cli/releases/download/v#{version}/pray_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "720a861e34075f039578ae9a4dd6805591099d294130874b5c0fc264519958be"
      url "https://github.com/jamesmagoo/pray-cli/releases/download/v#{version}/pray_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "feae00872e75b1a46066f04aa6a05ee48a84eb458201180f771ed24a7c91e6d2"
      url "https://github.com/jamesmagoo/pray-cli/releases/download/v#{version}/pray_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "962debb8b2bb32f2bba8ebd6b3702f672a70bbda650117d67f9f31f463ea8eea"
      url "https://github.com/jamesmagoo/pray-cli/releases/download/v#{version}/pray_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pray"
  desc "Prayers in your terminal"
  homepage "https://github.com/jamesmagoo/pray-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pray"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pray"]
    end
  end
  generate_completions_from_executable "pray", "completion",
    shell_parameter_format: :cobra

  # No zap stanza required
end
