# This file was generated by GoReleaser. DO NOT EDIT.
cask "pray" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "79c3cb44aeb39ffcf673d4010c911dfe4af61bcb8bd769b715a7a807a2522141"
      url "https://github.com/jamesmagoo/pray-cli/releases/download/v#{version}/pray_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e978bd1aa13ef7006f4265ca1a6900a0f6f26a589d5c565570c0e45031b61c62"
      url "https://github.com/jamesmagoo/pray-cli/releases/download/v#{version}/pray_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e753f254a99f388c931c7046d4d5e87e1218ff9b90e01aa1f5a527beed1ed566"
      url "https://github.com/jamesmagoo/pray-cli/releases/download/v#{version}/pray_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3ea56275641e8baf2b293cf1743966cb372cba0ae6609d8f3b0d94e67af04f9b"
      url "https://github.com/jamesmagoo/pray-cli/releases/download/v#{version}/pray_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pray"
  desc "Prayers in your terminal"
  homepage "https://github.com/jamesmagoo/pray-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pray"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pray"]
    end
  end
  generate_completions_from_executable "pray", "completion",
    shell_parameter_format: :cobra

  # No zap stanza required
end
